# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

# trying better markdown
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
  
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : CHAR Lab
tagline: Computing Hardware and Architecture Research
author :
  name : CHAR Lab
  email : charlab@hmc.edu
  github : charlab
#  twitter : charlab
#  feedburner : feedname

# List of authors for people page
author_ids: [jspjut, estorm, dhpark, fhannan, abagaria, pjolly]
# Author section for multiple author info
post_authors :
  jspjut :
    display_name : Josef Spjut
    job_title : Professor
    bio : 'Josef is a visiting assistant professor of computer
        engineering at Harvey Mudd College and a consulting researcher
	for NVIDIA. He received his Ph.D. from University of Utah and
	his B.S in Computer Engineering from University of California
	Riverside.'
    email : jspjut@g.hmc.edu
    web : http://jspjut.github.io/
    twitter :
    github : jspjut
    linkedin : josefspjut
# email, web, twitter, github, linkedin all optional
# recommended student job_title as "B.S. Engineering 2015"
  dshim :
    display_name : Da Eun Shim
    job_title : B.S. Engineering 2016
    bio : '.'
    email : dshim@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  mngai :
    display_name : Amy Ngai
    job_title : B.S. Engineering 2016
    bio : '.'
    email : mngai@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  relminyawi :
    display_name : Ramy Elminyawi
    job_title : B.S. Engineering 2016
    bio : '.'
    email : relminyawi@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  afishberg :
    display_name : Andrew Fishberg
    job_title : B.S. Engineering 2016
    bio : '.'
    email : afishberg@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  knlau :
    display_name : Kirklann Lau
    job_title : B.S. Engineering 2016
    bio : '.'
    email : knlau@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  rpiersall :
    display_name : Richard Piersall
    job_title : B.S. Engineering 2016
    bio : '.'
    email : rpiersall@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  szwilliams :
    display_name : Skyler Williams
    job_title : B.S. Computer Science 2016
    bio : '.'
    email : szwilliams@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
  lbrann :
    display_name : Louis Brann
    job_title : B.S. Computer Science 2016
    bio : '.'
    email : lbrann@g.hmc.edu
    web : 
    twitter : 
    github : 
    linkedin : 
# 2013-2014 members
  dhpark :
    display_name : Dong-hyeon Park
    job_title : B.S. Engineering 2014
    bio : 'Dong-hyeon graduated in 2014 and is now a Ph.D. student at Michigan.'
    email : dhpark@g.hmc.edu
    web : 
    twitter : 
    github : dhpark-hmc
    linkedin : donghyeonpark
  estorm :
    display_name : Eric Storm
    job_title : B.S. Engineering 2015
    bio : 'Eric is now a Clay-Wolkin Fellow.'
    email : estorm@g.hmc.edu
    web : 
    twitter : 
    github : EStorm21
    linkedin : 
  fhannan :
    display_name : Fabiha Hannan
    job_title : B.S. Engineering 2016
    bio : 'Fabiha is a grader for E85.'
    email : fhannan@g.hmc.edu
    web : 
    twitter : 
    github : fpjhannan
    linkedin : fpjhannan
  abagaria :
    display_name : Akhil Bagaria
    job_title : B.S. Engineering 2016
    bio : 'Akhil have moved on to projects with LAIR.'
    email : abagaria@hmc.edu
    web : http://abagaria.wordpress.com
    twitter : 
    github : abagaria
    linkedin : akhilbagaria
  pjolly :
    display_name : Paul Jolly
    job_title : B.S. Engineering 2016
    bio : 'Paul is a grader for E85.'
    email : pjolly@g.hmc.edu
    web : 
    twitter : 
    github : paul-jolly
    linkedin :
##### End authors section

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://charlab.github.io

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : charlab
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google
    google : 
        tracking_id : 'UA-43681956-2'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : tweet
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
  posts_collate :
    provider : "custom"

